server:
  port: 8080
  #  优化关闭
  shutdown: graceful
  servlet:
    context-path: /questionnaire
    encoding:
      enabled: false
  tomcat:
    baseDir: /DATA/app/ibeplus-springboot-questionnaire
    accesslog:
      enabled: true
      max-days: 3
    accept-count: 1500
    connection-timeout: 20s
    threads:
      max: 1500
      min-spare: 50

  #
spring:
  aop:
    auto: true
    proxy-target-class: false
#  mvc:
#    formcontent:
#      filter:
#        enabled: true
#    hiddenmethod:
#      filter:
#        enabled: false

  lifecycle:
    timeout-per-shutdown-phase: 60s
  datasource:  # 数据库设置
    url: jdbc:mysql://localhost:3306/questionnaire?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CST
    username: root
    password: 813256
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis: # mybatis 相关配置
  # mapper相关配置
  mapper-locations: classpath:mapping/*Mapper.xml
  # 批量配置该实体类以类相同的别名
  type-aliases-package: com.freefly.questionnaire.dto

# knife4j相关配置 未生效
knife4j:
  production: true
  basic:  # 开启Swagger的Basic认证功能,默认是false
    enable: true   # Basic认证用户名
    username: hjwu # Basic用户名
    password: hjwu   # Basic认证密码