server:
  port: ${override.server.port}
#  优化关闭
  shutdown: graceful
  servlet:
    context-path: ${override.server.servlet.context-path}
  tomcat:
    baseDir: ${override.server.tomcat.baseDir}
    accesslog:
      enabled: true
      max-days: 3
    max-threads:  1500
    accept-count: 1500
    min-spare-threads: 50
    protocol: org.apache.coyote.http11.Http11Nio2Protocol
    remoteip:
      internal-proxies: ${override.server.tomcat.internal-proxies}
      remote-ip-header: x-forwarded-for
      protocol-header: X-forwarded-Proto
    connection-timeout: 20s


#
spring:
  aop:
    auto: true
    proxy-target-class: false
  mvc:
    formcontent:
      filter:
        enabled: false
    hiddenmethod:
      filter:
        enabled: false
  http:
    encoding:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 60s

#spring:
#  devtools:
#    add-properties: false

# swagger配置
swagger:
  markdowns: classpath:markdown/*